<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://htng.org/2014B" xmlns:xs="http://www.w3.org/2001/XMLSchema" name="CommissionPayment" targetNamespace="http://htng.org/2014B">
	<wsdl:import namespace="http://htng.org/2014B" location="HTNG_CommonMessages.wsdl"/>
	<wsdl:portType name="CommissionPayment">
		<wsdl:operation name="PayCommission">
			<wsdl:input message="tns:HTNG_HotelCommissionPaymentRQ"/>
			<wsdl:output message="tns:HTNG_HotelCommissionPaymentRS"/>
		</wsdl:operation>
	</wsdl:portType>
</wsdl:definitions>




