<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://htng.org/2014B" xmlns:xs="http://www.w3.org/2001/XMLSchema" name="DeviceRegistrationManagement" targetNamespace="http://htng.org/2014B">
	<wsdl:import namespace="http://htng.org/2014B" location="HTNG_CommonMessages.wsdl"/>
	<wsdl:portType name="DeviceRegistrationManagement">
		<wsdl:operation name="RegisterDevices">
			<wsdl:input message="tns:HTNG_DeviceRegistrationRQ"/>
			<wsdl:output message="tns:HTNG_DeviceRegistrationRS"/>
		</wsdl:operation>
		<wsdl:operation name="CreateDeviceCapabilityProfile">
			<wsdl:input message="tns:HTNG_DeviceCapabilityProfileRQ"/>
			<wsdl:output message="tns:HTNG_DeviceCapabilityProfileRS"/>
		</wsdl:operation>
		<wsdl:operation name="DiscoverDevices">
			<wsdl:input message="tns:HTNG_DeviceSearchRQ"/>
			<wsdl:output message="tns:HTNG_DeviceSearchRS"/>
		</wsdl:operation>
	</wsdl:portType>
</wsdl:definitions>


