<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://htng.org/2014B" xmlns:xs="http://www.w3.org/2001/XMLSchema" name="DeviceCommandAndControl" targetNamespace="http://htng.org/2014B">
  <wsdl:import namespace="http://htng.org/2014B" location="HTNG_CommonMessages.wsdl"/>
  <wsdl:portType name="DeviceCommandAndControl">
    <wsdl:operation name="DeviceCommand">
      <wsdl:input message="tns:HTNG_DeviceCommandRQ"/>
      <wsdl:output message="tns:HTNG_DeviceCommandRS"/>
    </wsdl:operation>
    <wsdl:operation name="DeviceStatus">
      <wsdl:input message="tns:HTNG_DeviceStatusRQ"/>
      <wsdl:output message="tns:HTNG_DeviceStatusRS"/>
    </wsdl:operation>
    <wsdl:operation name="DeviceEvent">
      <wsdl:input message="tns:HTNG_DeviceEventRQ"/>
      <wsdl:output message="tns:HTNG_DeviceEventRS"/>
    </wsdl:operation>
  </wsdl:portType>
</wsdl:definitions>
