<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://htng.org/2014B" xmlns:xs="http://www.w3.org/2001/XMLSchema" name="FolioManagement" targetNamespace="http://htng.org/2014B">
	<wsdl:import namespace="http://htng.org/2014B" location="HTNG_CommonMessages.wsdl"/>
	<wsdl:portType name="FolioManagement">
		<wsdl:operation name="PushFolio">
			<wsdl:input message="tns:HTNG_HotelFolioNotifRQ"/>
			<wsdl:output message="tns:HTNG_HotelFolioNotifRS"/>
		</wsdl:operation>
		<wsdl:operation name="RetrieveFolio">
			<wsdl:input message="tns:HTNG_HotelFolioRQ"/>
			<wsdl:output message="tns:HTNG_HotelFolioRS"/>
		</wsdl:operation>
	</wsdl:portType>
</wsdl:definitions>




