<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://htng.org/2014B" xmlns:xs="http://www.w3.org/2001/XMLSchema" name="GuestCommunications" targetNamespace="http://htng.org/2014B">
	<wsdl:import namespace="http://htng.org/2014B" location="HTNG_CommonMessages.wsdl"/>
	<wsdl:portType name="GuestCommunications">
		<wsdl:operation name="RetrieveMessages">
			<wsdl:input message="tns:HTNG_ProfileMessageRQ"/>
			<wsdl:output message="tns:HTNG_ProfileMessageRS"/>
		</wsdl:operation>
		<wsdl:operation name="UpdateMessageStatus">
			<wsdl:input message="tns:HTNG_ProfileMessageStatusRQ"/>
			<wsdl:output message="tns:HTNG_ProfileMessageStatusRS"/>
		</wsdl:operation>
	</wsdl:portType>
</wsdl:definitions>




