<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://htng.org/2014B" xmlns:xs="http://www.w3.org/2001/XMLSchema" name="PublishAndSubscribe" targetNamespace="http://htng.org/2014B">
  <wsdl:import namespace="http://htng.org/2014B" location="HTNG_CommonMessages.wsdl"/>
  <wsdl:portType name="PublishAndSubscribe">
    <wsdl:operation name="GetAvailableSubscriptions">
      <wsdl:input message="tns:HTNG_SubscriptionsAvailableRQ"/>
      <wsdl:output message="tns:HTNG_SubscriptionsAvailableRS"/>
    </wsdl:operation>
    <wsdl:operation name="GetSubscriptionStatus">
      <wsdl:input message="tns:HTNG_SubscriptionStatusRQ"/>
      <wsdl:output message="tns:HTNG_SubscriptionStatusRS"/>
    </wsdl:operation>
  </wsdl:portType>
</wsdl:definitions>
