<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://htng.org/2014B" xmlns:xs="http://www.w3.org/2001/XMLSchema" name="ReservationStayStatus" targetNamespace="http://htng.org/2014B">
	<wsdl:import namespace="http://htng.org/2014B" location="HTNG_CommonMessages.wsdl"/>
	<wsdl:portType name="ReservationStayStatus">
		<wsdl:operation name="ProcessReservationCheckIn">
			<wsdl:input message="tns:OTA_HotelResNotifRQ"/>
			<wsdl:output message="tns:OTA_HotelResNotifRS"/>
		</wsdl:operation>
		<wsdl:operation name="ProcessReservationCheckOut">
			<wsdl:input message="tns:OTA_HotelResNotifRQ"/>
			<wsdl:output message="tns:OTA_HotelResNotifRS"/>
		</wsdl:operation>
	</wsdl:portType>
</wsdl:definitions>




