<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://htng.org/2014B" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:wsp="http://www.w3.org/ns/ws-policy" name="ReservationManagementBinding" targetNamespace="http://htng.org/2014B">
	<wsdl:import namespace="http://htng.org/2014B" location="ReservationManagementPort.wsdl"/>
	<wsdl:binding name="ReservationManagementBinding" type="tns:ReservationManagement">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<!-- Deprecation warning.  The ReservationManagementPortBinding binding will be disappearing -->
		<wsdl:operation name="RetrieveReservations">
			<soap:operation soapAction="http://htng.org/2014B/HTNG_KioskService#RetrieveReservations" style="document"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="ModifyReservation">
			<soap:operation soapAction="http://htng.org/2014B/HTNG_KioskService#ModifyReservation" style="document"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
</wsdl:definitions>



