<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://htng.org/2014B" xmlns:xs="http://www.w3.org/2001/XMLSchema" name="ServiceRecovery" targetNamespace="http://htng.org/2014B">
	<wsdl:import namespace="http://htng.org/2014B" location="HTNG_CommonMessages.wsdl"/>
	<wsdl:portType name="ServiceRecovery">
		<wsdl:operation name="CreateServiceIssue">
			<wsdl:input message="tns:HTNG_ServiceIssueCreateRQ"/>
			<wsdl:output message="tns:HTNG_ServiceIssueCreateRS"/>
		</wsdl:operation>
		<wsdl:operation name="ServiceIssueChanged">
			<wsdl:input message="tns:HTNG_ServiceIssueNotifRQ"/>
			<wsdl:output message="tns:HTNG_ServiceIssueNotifRS"/>
		</wsdl:operation>
		<wsdl:operation name="ReadServiceIssue">
			<wsdl:input message="tns:HTNG_ServiceIssueReadRQ"/>
			<wsdl:output message="tns:HTNG_ServiceIssueReadRS"/>
		</wsdl:operation>
	</wsdl:portType>
</wsdl:definitions>


