<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://htng.org/2014B" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:wsp="http://www.w3.org/ns/ws-policy" name="ServiceRecoveryBinding" targetNamespace="http://htng.org/2014B">
	<wsdl:import namespace="http://htng.org/2014B" location="ServiceRecoveryPort.wsdl"/>
	<wsdl:binding name="ServiceRecoveryBinding" type="tns:ServiceRecovery">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="CreateServiceIssue">
			<soap:operation soapAction="http://htng.org/2014B/HTNG_ServiceIssueService#CreateServiceIssue" style="document"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="ServiceIssueChanged">
			<soap:operation soapAction="http://htng.org/2014B/HTNG_ServiceIssueService#ServiceIssueChanged" style="document"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="ReadServiceIssue">
			<soap:operation soapAction="http://htng.org/2014B/HTNG_ServiceIssueService#ReadServiceIssue" style="document"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
</wsdl:definitions>


