<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://htng.org/2014B" xmlns:xs="http://www.w3.org/2001/XMLSchema" name="StayNotification" targetNamespace="http://htng.org/2014B">
	<wsdl:import namespace="http://htng.org/2014B" location="HTNG_CommonMessages.wsdl"/>
	<wsdl:portType name="StayNotification">
		<wsdl:operation name="CheckedIn">
			<wsdl:input message="tns:HTNG_HotelCheckInNotifRQ"/>
			<wsdl:output message="tns:HTNG_HotelCheckInNotifRS"/>
		</wsdl:operation>
		<wsdl:operation name="CheckedOut">
			<wsdl:input message="tns:HTNG_HotelCheckOutNotifRQ"/>
			<wsdl:output message="tns:HTNG_HotelCheckOutNotifRS"/>
		</wsdl:operation>
		<wsdl:operation name="StayUpdated">
			<wsdl:input message="tns:HTNG_HotelStayUpdateNotifRQ"/>
			<wsdl:output message="tns:HTNG_HotelStayUpdateNotifRS"/>
		</wsdl:operation>
		<wsdl:operation name="RoomMoved">
			<wsdl:input message="tns:HTNG_HotelRoomMoveNotifRQ"/>
			<wsdl:output message="tns:HTNG_HotelRoomMoveNotifRS"/>
		</wsdl:operation>
	</wsdl:portType>
</wsdl:definitions>




